### ISSUE TITLE
Actions: build and deploy

### ISSUE THREAD

**Issue by Adean64** [TCMG-412-Group-6/TCMG-412-Group-6.github.io#1]
The bot is currently hung on queueing the current build.

**Comment by Adean64** [comment]
Attempting to cancel workflow fails. 
Deleting the previous cancelled workflow also failed.

**Comment by Adean64** [comment]
The root cause seems to be attributed to github, where Github Actions is experiencing degraded functionality/a partial outage.

**Comment by Logan-MacDonald** [comment]
The build is now working.
